### ISSUE TITLE
how to run it on android ?  

### ISSUE THREAD

**Issue by parth721** [revan/delay#1]
Hi Revan , I am Partha, also a undergrad student. Fewdays back I was studying about persuasive techology. And I am excited to say I didn't found any application like "delay". In playstore application it is not available.  you deserve lots of appreciation for building such application. 
Would  you like to show some light on the topic :  how to run this on android.

Thank you

**Comment by parth721** [comment]
![Screenshot from 2024-07-31 22-50-16](https://github.com/user-attachments/assets/19448d9b-9533-4a7c-b492-e2266b654374)

I tried to build its apk, Getting some errors  on android studio. Now finding fix for them. (working on app dev first time).

**Comment by revan** [comment]
Hi there -- after four years of inactivity the app store listing was taken down automatically!

I haven't built this in a moment, but it looks like the github action (which runs `./gradlew assembleDebug --stacktrace` with JDK 1.8) still works. Are you matching this version?

(Or if you just need the APK, download the artifact from the action run here: https://github.com/revan/delay/actions/runs/10186968751)

**Comment by parth721** [comment]
okay it pause while creating the app shortcut. (using android 11 go edition).
After reading about persuasive technology. I turned my phone to greyscale, startrd using minimal launcher, using extension to delay website opening. 😄
 
Now I also need to learn basics of app-dev  to run it on phone. 😅

I have a question. 
how you manage dev along with data structure and algorithm ? because in india interviewer mainly ask data structure and algorithm and students here work more  towards dev or toward dsa.
in my first 1.5yr of college give time to learn language , then dev( cryptography, webdev, computer vision, ml, k8s, docker, ...) and managing dsa with them become chaotic. 

did you do competitive programming ?  how to make yourself good at DSA?

Thank you for the help
